#!/bin/bash

# Pull the latest version of UCP
docker image pull docker/ucp:3.1.6

# Install UCP
docker container run --rm -it --name ucp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  docker/ucp:3.1.6 install \
  --force-minimums \
  --host-address 192.168.0.111 \
  --interactive
